apiVersion: v1
kind: Service
metadata:
  name: frontend-rampup-final-service
spec:
  type: NodePort
  selector:
    app: frontend-rampup-final
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
